### PR TITLE
small improvements for running the install

### PR DESCRIPTION
**Pull request by klarrio-dlamb**
Some minor improvements to the install:
* use the env file variables when cleaning and creating the sample DB values
* gitignore the retrieved sample file
* use the default container name created by docker-compose for the db hostname in the example
Had been seeing this:
```
Dropping database dispatch if it already exists...
Creating dispatch_postgres_run ... done
dropdb: error: could not connect to database template1: could not translate host name "postgres" to address: Name or service not known
ERROR: 1
Cleaning up...
```

Not sure why I was getting this now, but might be better to refer to that than just 'postgres'?..  Optional.

### CODE REVIEW

**Comment by mvilanova** [comment]
Changes look good. Let me check the `DATABASE_HOSTNAME` change locally before merging the changes.

**Comment by mvilanova** [comment]
I've got the same error as you even when `DATABASE_HOSTNAME` is set to `dispatch_postgres_1`. I'll keep looking to see what's causing it...

**Comment by mvilanova** [comment]
The command was failing because postgres wasn't starting due to a version mismatch. Do you see the following error when you run `docker logs dispatch_postgres_1`? If so, can you run `docker volume rm dispatch-postgres` and then try again?
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-03-10 20:56:32.486 UTC [1] FATAL:  database files are incompatible with server
2021-03-10 20:56:32.486 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 12.6 (Debian 12.6-1.pgdg100+1).
```

**Comment by klarrio-dlamb** [comment]
> The command was failing because postgres wasn't starting due to a version mismatch. Do you see the following error when you run `docker logs dispatch_postgres_1`? If so, can you run `docker volume rm dispatch-postgres` and then try again?
> 
> ```
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 2021-03-10 20:56:32.486 UTC [1] FATAL:  database files are incompatible with server
> 2021-03-10 20:56:32.486 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 12.6 (Debian 12.6-1.pgdg100+1).
> ```

Thanks - yes - had been getting that same error and removed the volume. I was pretty sure I was still getting the hostname problem after doing this, and hence played with the hostname..  but don't have a good record of my sequencing.  Perhaps I did discover this part way through.  Anyway - thanks!

**Pull request merged**
