### PR TITLE
Readme correct filepath, docker compose correct url

### PR DESCRIPTION
**Pull request by Mitsuwa**
# What

This pr is made to fix a couple of things.  First the install script in the readme isn't located in docker folder in this repo, its in the root

Also this sets the context for dispatch build to point at the github repo for dispatch, since theres no dispatch folder, when I try to `docker-compose build` before this, I get

`ERROR: build path /path/to/dispatch-docker/dispatch either does not exist, is not accessible, or is not a valid URL.`

# Testing

This repo actually still doesnt build, im wondering how it ever did???  Am i missing some installs somewhere or something that arent called out in this readme or https://hawkins.gitbook.io/dispatch/installation

I'm still getting `ERROR: Service 'web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder448268992/.nvmrc: no such file or directory` when I try to build the docker image, everything completes fine except nvmrc doesn't exist.

also tr seems to be failing in the install script

```
$ head /dev/urandom | tr -dc "a-z0-9@#%^&*(-_=+)"
tr: Illegal byte sequence
```

```
$ ./install.sh
Checking minimum requirements...
Removing network dispatch_default
WARNING: Network dispatch_default not found.

Creating volumes for persistent storage...
Created dispatch-postgres.

./.env already exists, skipped creation.
Creating ./requirements.txt...

Generating secret key...
tr: Illegal byte sequence
Secret key written to ./.env

Building and tagging Docker images...

Pulling postgres           ...
Pulling web                ...
Pulling postgres           ... done
Pulling web                ... done
Pulling dispatch-scheduler ... done
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
Cleaning up...
```

Also, what is this docker build line supposed to do? 

https://github.com/Netflix/dispatch-docker/blob/master/install.sh#L80

```
$ docker build
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
```

you can see the install script fail also

### CODE REVIEW

**Comment by Mitsuwa** [comment]
@kevgliss

**Comment by kevgliss** [comment]
Thanks for the PR, you're correct this docker image was/is a bit broken. Unfortunately, we ran out of time before some other deadlines. I will be taking a look at it this week to get it up to par. We don't run Dispatch on docker internally so please bear with me.

**Comment by lastlee** [comment]
I believe you can fix the issues with the "Illegal byte sequence" by specifying `LC_CTYPE=C`:

```
SECRET_KEY=$(head /dev/urandom | env LC_CTYPE=C tr -dc "a-z0-9@#%^&*(-_=+)" | head -c 50 | sed -e 's/[\/&]/\\&/g')
```

**Comment by AliceLoeser** [comment]
@lastlee thanks, it works for me, I opened a PR!

**Pull request merged**
